service: timeblock
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModuels: true
provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatments:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'sts:*'
      Resource: '*'

functions:
  createItem:
    handler: index.createItem
    events:
      - http:
          path: /item
          method: post
          cors: true
  createItemGroup:
    handler: index.createItemGroup
    events:
      - http:
          path: /group
          method: post
          cors: true
  getItems:
    handler: index.getItems
    events:
      - http:
          path: /items
          method: get
          cors: true
  getItemGroups:
    handler: index.getItemGroups
    events:
      - http:
          path: /groups
          method: get
          cors: true
  updateItem:
    handler: index.updateItem
    events:
      - http:
          path: /item
          method: put
          cors: true
  deleteItem:
    handler: index.deleteItem
    events:
      - http:
          path: /item
          method: delete
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
