service: timeblock
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModuels: true
provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatments:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:*'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'sts:*'
      Resource: '*'

functions:
  getUser:
    handler: index.getUser
    events:
      - http:
          path: /user
          method: get
          cors: true
  createUserItem:
    handler: index.createUserItem
    events:
      - http:
          path: /user-item
          method: post
          cors: true
  updateItem:
    handler: index.updateItem
    events:
      - http:
          path: /item
          method: put
          cors: true
  deleteItem:
    handler: index.deleteItem
    events:
      - http:
          path: /item
          method: delete
          cors: true

  saveList:
    handler: index.saveList
    events:
      - http:
          path: /save-list
          method: post
          cors: true
plugins:
  - serverless-webpack
  - serverless-offline
